# Default values for golang.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: dictybase/event-messenger
  tag: latest
  pullPolicy: IfNotPresent

# Level of log
logLevel: debug

##  Arangodb database
# connection endpoint http or https (ssl)
endpoint: https

dictybaseConfiguration:
  secrets:
    name: dictybase-configuration
    githubToken: eventMessenger.github.token
    arangopass: arangodb.password
  configMap:
    name: dictybase-configuration
    arangouser: arangodb.user
    database: arangodb.modware-annotation

service:
  name: webhook-onto-server
  type: ClusterIP
  port: 9004

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
