name: Build
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: set up golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.15
      - name: check out code
        uses: actions/checkout@v2
      - name: unit test
        run: go test -parallel 3 -covermode=atomic -coverprofile=profile.cov -v ./...
        env:
          GOPROXY: https://proxy.golang.org
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v1.2.2
        with:
            file: ./profile.cov
            token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: set up golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.15
      - name: check out code
        uses: actions/checkout@v2
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
      - name: cache docker layers
        uses: actions/cache@v2.1.4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: log into dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: get short sha
        id: vars
        run: |
          sha=$(git rev-parse --short HEAD)
          echo ::set-output name=image_tag::${sha}
      - name: docker build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: build/package/Dockerfile
          tags: dictybase/${{ github.event.repository.name }}:develop-${{ steps.vars.outputs.image_tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
