name: Continuous integration
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: set up golang
        uses: actions/setup-go@v2
        with:
            go-version: 1.16.5
      - name: check out code
        uses: actions/checkout@v2
      - name: unit test
        run: go test -parallel 2 -covermode=atomic -coverprofile=profile.cov -v ./...
        env:
          GOPROXY: https://proxy.golang.org
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v1.3.1
        with:
            file: ./profile.cov
            token: ${{ secrets.CODECOV_TOKEN }}
