name: Continuous build
on: 
 push:
   branches:
     - develop
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: set up golang
        uses: actions/setup-go@v2-beta
        with:
            go-version: 1.13.10
      - name: check out code
        uses: actions/checkout@v2
      - name: unit test
        run: go test -parallel 2 -covermode=atomic -coverprofile=profile.cov -v ./...
        env:
          GOPROXY: https://proxy.golang.org
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v1.0.6
        with:
            file: ./profile.cov
            token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs: test
    runs-on: ubuntu-18.04
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: image build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD  }}
          repository: dictybase/event-messenger
          add_git_labels: true
          tag_with_sha: true
          dockerfile: build/package/Dockerfile
