name: Continuous integration
on:
  push:
    branches:
      - develop
jobs:
  call-testcov:
    uses: dictyBase/workflows/.github/workflows/golang-testcov.yml@develop
    secrets: inherit
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref_name }}
  call-publication-docker-build:
    needs: call-testcov
    uses: dictyBase/workflows/.github/workflows/build-publish-image.yaml@develop
    secrets: inherit
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref_name }}
      image: event-messenger
      dockerfile: build/package/Dockerfile 
      namespace: dictybase
