name: Lint Golang code
on:
  pull_request:
    branches-ignore:
      - master
jobs:
  call-lint:
    uses: dictyBase/workflows/.github/workflows/golang-lint.yaml@develop
    secrets: inherit
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref_name }}
