name: Test coverage
on: pull_request
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: set up golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.5
      - name: check out code
        uses: actions/checkout@v3.1.0
      - name: unit test
        run: go test -parallel 3 -covermode=atomic -coverprofile=profile.cov -v ./...
        env:
          GOPROXY: https://proxy.golang.org
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
            file: ./profile.cov
            token: ${{ secrets.CODECOV_TOKEN }}
