name: Test coverage
on: pull_request
jobs:
  call-testcov:
    uses: dictyBase/workflows/.github/workflows/golang-testcov.yaml@develop
    secrets: inherit
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref_name }}
